language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env: SYMFONY_VERSION=2.7.*

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: SYMFONY_VERSION=2.5.*
    - php: 5.5
      env: SYMFONY_VERSION=2.6.*
    - php: 5.5
      env: SYMFONY_VERSION=2.8.*
    - php: 5.5
      env: SYMFONY_VERSION=3.0.*
    - php: 5.6
      env: SYMFONY_VERSION=2.5.*
    - php: 5.6
      env: SYMFONY_VERSION=2.6.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - composer self-update
  - mkdir -p build/logs
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-source

script:
  - bin/phpunit

after_script:
  - bin/coveralls -v
