language: php

services:
  - redis-server

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env: SYMFONY_VERSION=2.7.*

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: SYMFONY_VERSION=2.5.*
    - php: 5.5
      env: SYMFONY_VERSION=2.6.*
    - php: 5.5
      env: SYMFONY_VERSION=2.8.*
    - php: 5.5
      env: SYMFONY_VERSION=3.0.*
    - php: 5.6
      env: SYMFONY_VERSION=2.5.*
    - php: 5.6
      env: SYMFONY_VERSION=2.6.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*

before_install:
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then pecl channel-update pecl.php.net; fi;
  - if [[ $TRAVIS_PHP_VERSION =~ 5.[4-6] ]]; then echo yes | pecl install apcu-4.0.10; fi;
  - if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then echo yes | pecl install apcu; fi;
  - composer self-update
  - mkdir -p build/logs
  - if [[ $SYMFONY_VERSION != "" ]]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-source

script:
  - bin/phpunit

after_success:
  - if [[ $TRAVIS_PHP_VERSION == "5.6" && $SYMFONY_VERSION == "2.8.*" ]]; then travis_retry php bin/coveralls -v; fi;
